# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _doa_swig
else:
    import _doa_swig

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def high_res_timer_now() -> "gr::high_res_timer_type":
    r"""high_res_timer_now() -> gr::high_res_timer_type"""
    return _doa_swig.high_res_timer_now()

def high_res_timer_now_perfmon() -> "gr::high_res_timer_type":
    r"""high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
    return _doa_swig.high_res_timer_now_perfmon()

def high_res_timer_tps() -> "gr::high_res_timer_type":
    r"""high_res_timer_tps() -> gr::high_res_timer_type"""
    return _doa_swig.high_res_timer_tps()

def high_res_timer_epoch() -> "gr::high_res_timer_type":
    r"""high_res_timer_epoch() -> gr::high_res_timer_type"""
    return _doa_swig.high_res_timer_epoch()
class autocorrelate(object):
    r"""Proxy of C++ gr::doa::autocorrelate class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(inputs: "int", snapshot_size: "int", overlap_size: "int", avg_method: "int") -> "gr::doa::autocorrelate::sptr":
        r"""make(int inputs, int snapshot_size, int overlap_size, int avg_method) -> autocorrelate_sptr"""
        return _doa_swig.autocorrelate_make(inputs, snapshot_size, overlap_size, avg_method)
    __swig_destroy__ = _doa_swig.delete_autocorrelate

# Register autocorrelate in _doa_swig:
_doa_swig.autocorrelate_swigregister(autocorrelate)

def autocorrelate_make(inputs: "int", snapshot_size: "int", overlap_size: "int", avg_method: "int") -> "gr::doa::autocorrelate::sptr":
    r"""autocorrelate_make(int inputs, int snapshot_size, int overlap_size, int avg_method) -> autocorrelate_sptr"""
    return _doa_swig.autocorrelate_make(inputs, snapshot_size, overlap_size, avg_method)

class autocorrelate_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::autocorrelate > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(autocorrelate_sptr self) -> autocorrelate_sptr
        __init__(autocorrelate_sptr self, autocorrelate p) -> autocorrelate_sptr
        """
        _doa_swig.autocorrelate_sptr_swiginit(self, _doa_swig.new_autocorrelate_sptr(*args))

    def __deref__(self) -> "gr::doa::autocorrelate *":
        r"""__deref__(autocorrelate_sptr self) -> autocorrelate"""
        return _doa_swig.autocorrelate_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_autocorrelate_sptr

    def make(self, inputs: "int", snapshot_size: "int", overlap_size: "int", avg_method: "int") -> "gr::doa::autocorrelate::sptr":
        r"""make(autocorrelate_sptr self, int inputs, int snapshot_size, int overlap_size, int avg_method) -> autocorrelate_sptr"""
        return _doa_swig.autocorrelate_sptr_make(self, inputs, snapshot_size, overlap_size, avg_method)

    def history(self) -> "unsigned int":
        r"""history(autocorrelate_sptr self) -> unsigned int"""
        return _doa_swig.autocorrelate_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(autocorrelate_sptr self, int which, int delay)
        declare_sample_delay(autocorrelate_sptr self, unsigned int delay)
        """
        return _doa_swig.autocorrelate_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(autocorrelate_sptr self, int which) -> unsigned int"""
        return _doa_swig.autocorrelate_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(autocorrelate_sptr self, int multiple)"""
        return _doa_swig.autocorrelate_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(autocorrelate_sptr self) -> int"""
        return _doa_swig.autocorrelate_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(autocorrelate_sptr self) -> double"""
        return _doa_swig.autocorrelate_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(autocorrelate_sptr self) -> uint64_t"""
        return _doa_swig.autocorrelate_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(autocorrelate_sptr self) -> uint64_t"""
        return _doa_swig.autocorrelate_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(autocorrelate_sptr self) -> bool"""
        return _doa_swig.autocorrelate_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(autocorrelate_sptr self) -> bool"""
        return _doa_swig.autocorrelate_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(autocorrelate_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.autocorrelate_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(autocorrelate_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.autocorrelate_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(autocorrelate_sptr self, std::string level)"""
        return _doa_swig.autocorrelate_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(autocorrelate_sptr self) -> std::string"""
        return _doa_swig.autocorrelate_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(autocorrelate_sptr self) -> int"""
        return _doa_swig.autocorrelate_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(autocorrelate_sptr self, int m)"""
        return _doa_swig.autocorrelate_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(autocorrelate_sptr self)"""
        return _doa_swig.autocorrelate_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(autocorrelate_sptr self) -> bool"""
        return _doa_swig.autocorrelate_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(autocorrelate_sptr self, int m)"""
        return _doa_swig.autocorrelate_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(autocorrelate_sptr self) -> int"""
        return _doa_swig.autocorrelate_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(autocorrelate_sptr self, int i) -> long"""
        return _doa_swig.autocorrelate_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(autocorrelate_sptr self, long max_output_buffer)
        set_max_output_buffer(autocorrelate_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.autocorrelate_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(autocorrelate_sptr self, int i) -> long"""
        return _doa_swig.autocorrelate_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(autocorrelate_sptr self, long min_output_buffer)
        set_min_output_buffer(autocorrelate_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.autocorrelate_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(autocorrelate_sptr self, int which) -> float
        pc_input_buffers_full(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(autocorrelate_sptr self, int which) -> float
        pc_input_buffers_full_avg(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(autocorrelate_sptr self, int which) -> float
        pc_input_buffers_full_var(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(autocorrelate_sptr self, int which) -> float
        pc_output_buffers_full(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(autocorrelate_sptr self, int which) -> float
        pc_output_buffers_full_avg(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(autocorrelate_sptr self, int which) -> float
        pc_output_buffers_full_var(autocorrelate_sptr self) -> pmt_vector_float
        """
        return _doa_swig.autocorrelate_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(autocorrelate_sptr self) -> float"""
        return _doa_swig.autocorrelate_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(autocorrelate_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.autocorrelate_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(autocorrelate_sptr self)"""
        return _doa_swig.autocorrelate_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(autocorrelate_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.autocorrelate_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(autocorrelate_sptr self) -> int"""
        return _doa_swig.autocorrelate_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(autocorrelate_sptr self) -> int"""
        return _doa_swig.autocorrelate_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(autocorrelate_sptr self, int priority) -> int"""
        return _doa_swig.autocorrelate_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(autocorrelate_sptr self) -> std::string"""
        return _doa_swig.autocorrelate_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(autocorrelate_sptr self) -> std::string"""
        return _doa_swig.autocorrelate_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(autocorrelate_sptr self) -> io_signature_sptr"""
        return _doa_swig.autocorrelate_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(autocorrelate_sptr self) -> io_signature_sptr"""
        return _doa_swig.autocorrelate_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(autocorrelate_sptr self) -> long"""
        return _doa_swig.autocorrelate_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(autocorrelate_sptr self) -> basic_block_sptr"""
        return _doa_swig.autocorrelate_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(autocorrelate_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.autocorrelate_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(autocorrelate_sptr self) -> std::string"""
        return _doa_swig.autocorrelate_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(autocorrelate_sptr self, std::string name)"""
        return _doa_swig.autocorrelate_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(autocorrelate_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.autocorrelate_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(autocorrelate_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.autocorrelate_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(autocorrelate_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.autocorrelate_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(autocorrelate_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.autocorrelate_sptr_message_subscribers(self, which_port)

# Register autocorrelate_sptr in _doa_swig:
_doa_swig.autocorrelate_sptr_swigregister(autocorrelate_sptr)


autocorrelate_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
autocorrelate = autocorrelate.make;

class MUSIC_lin_array(object):
    r"""Proxy of C++ gr::doa::MUSIC_lin_array class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(norm_spacing: "float", num_targets: "int", num_ant_ele: "int", pspectrum_len: "int") -> "gr::doa::MUSIC_lin_array::sptr":
        r"""make(float norm_spacing, int num_targets, int num_ant_ele, int pspectrum_len) -> MUSIC_lin_array_sptr"""
        return _doa_swig.MUSIC_lin_array_make(norm_spacing, num_targets, num_ant_ele, pspectrum_len)
    __swig_destroy__ = _doa_swig.delete_MUSIC_lin_array

# Register MUSIC_lin_array in _doa_swig:
_doa_swig.MUSIC_lin_array_swigregister(MUSIC_lin_array)

def MUSIC_lin_array_make(norm_spacing: "float", num_targets: "int", num_ant_ele: "int", pspectrum_len: "int") -> "gr::doa::MUSIC_lin_array::sptr":
    r"""MUSIC_lin_array_make(float norm_spacing, int num_targets, int num_ant_ele, int pspectrum_len) -> MUSIC_lin_array_sptr"""
    return _doa_swig.MUSIC_lin_array_make(norm_spacing, num_targets, num_ant_ele, pspectrum_len)

class MUSIC_lin_array_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::MUSIC_lin_array > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(MUSIC_lin_array_sptr self) -> MUSIC_lin_array_sptr
        __init__(MUSIC_lin_array_sptr self, MUSIC_lin_array p) -> MUSIC_lin_array_sptr
        """
        _doa_swig.MUSIC_lin_array_sptr_swiginit(self, _doa_swig.new_MUSIC_lin_array_sptr(*args))

    def __deref__(self) -> "gr::doa::MUSIC_lin_array *":
        r"""__deref__(MUSIC_lin_array_sptr self) -> MUSIC_lin_array"""
        return _doa_swig.MUSIC_lin_array_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_MUSIC_lin_array_sptr

    def make(self, norm_spacing: "float", num_targets: "int", num_ant_ele: "int", pspectrum_len: "int") -> "gr::doa::MUSIC_lin_array::sptr":
        r"""make(MUSIC_lin_array_sptr self, float norm_spacing, int num_targets, int num_ant_ele, int pspectrum_len) -> MUSIC_lin_array_sptr"""
        return _doa_swig.MUSIC_lin_array_sptr_make(self, norm_spacing, num_targets, num_ant_ele, pspectrum_len)

    def history(self) -> "unsigned int":
        r"""history(MUSIC_lin_array_sptr self) -> unsigned int"""
        return _doa_swig.MUSIC_lin_array_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(MUSIC_lin_array_sptr self, int which, int delay)
        declare_sample_delay(MUSIC_lin_array_sptr self, unsigned int delay)
        """
        return _doa_swig.MUSIC_lin_array_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(MUSIC_lin_array_sptr self, int which) -> unsigned int"""
        return _doa_swig.MUSIC_lin_array_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(MUSIC_lin_array_sptr self, int multiple)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(MUSIC_lin_array_sptr self) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(MUSIC_lin_array_sptr self) -> double"""
        return _doa_swig.MUSIC_lin_array_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(MUSIC_lin_array_sptr self) -> uint64_t"""
        return _doa_swig.MUSIC_lin_array_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(MUSIC_lin_array_sptr self) -> uint64_t"""
        return _doa_swig.MUSIC_lin_array_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(MUSIC_lin_array_sptr self) -> bool"""
        return _doa_swig.MUSIC_lin_array_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(MUSIC_lin_array_sptr self) -> bool"""
        return _doa_swig.MUSIC_lin_array_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(MUSIC_lin_array_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.MUSIC_lin_array_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(MUSIC_lin_array_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.MUSIC_lin_array_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(MUSIC_lin_array_sptr self, std::string level)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(MUSIC_lin_array_sptr self) -> std::string"""
        return _doa_swig.MUSIC_lin_array_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(MUSIC_lin_array_sptr self) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(MUSIC_lin_array_sptr self, int m)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(MUSIC_lin_array_sptr self)"""
        return _doa_swig.MUSIC_lin_array_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(MUSIC_lin_array_sptr self) -> bool"""
        return _doa_swig.MUSIC_lin_array_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(MUSIC_lin_array_sptr self, int m)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(MUSIC_lin_array_sptr self) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(MUSIC_lin_array_sptr self, int i) -> long"""
        return _doa_swig.MUSIC_lin_array_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(MUSIC_lin_array_sptr self, long max_output_buffer)
        set_max_output_buffer(MUSIC_lin_array_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.MUSIC_lin_array_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(MUSIC_lin_array_sptr self, int i) -> long"""
        return _doa_swig.MUSIC_lin_array_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(MUSIC_lin_array_sptr self, long min_output_buffer)
        set_min_output_buffer(MUSIC_lin_array_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.MUSIC_lin_array_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(MUSIC_lin_array_sptr self, int which) -> float
        pc_input_buffers_full(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(MUSIC_lin_array_sptr self, int which) -> float
        pc_input_buffers_full_avg(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(MUSIC_lin_array_sptr self, int which) -> float
        pc_input_buffers_full_var(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(MUSIC_lin_array_sptr self, int which) -> float
        pc_output_buffers_full(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(MUSIC_lin_array_sptr self, int which) -> float
        pc_output_buffers_full_avg(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(MUSIC_lin_array_sptr self, int which) -> float
        pc_output_buffers_full_var(MUSIC_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.MUSIC_lin_array_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(MUSIC_lin_array_sptr self) -> float"""
        return _doa_swig.MUSIC_lin_array_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(MUSIC_lin_array_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(MUSIC_lin_array_sptr self)"""
        return _doa_swig.MUSIC_lin_array_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(MUSIC_lin_array_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.MUSIC_lin_array_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(MUSIC_lin_array_sptr self) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(MUSIC_lin_array_sptr self) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(MUSIC_lin_array_sptr self, int priority) -> int"""
        return _doa_swig.MUSIC_lin_array_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(MUSIC_lin_array_sptr self) -> std::string"""
        return _doa_swig.MUSIC_lin_array_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(MUSIC_lin_array_sptr self) -> std::string"""
        return _doa_swig.MUSIC_lin_array_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(MUSIC_lin_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.MUSIC_lin_array_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(MUSIC_lin_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.MUSIC_lin_array_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(MUSIC_lin_array_sptr self) -> long"""
        return _doa_swig.MUSIC_lin_array_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(MUSIC_lin_array_sptr self) -> basic_block_sptr"""
        return _doa_swig.MUSIC_lin_array_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(MUSIC_lin_array_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.MUSIC_lin_array_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(MUSIC_lin_array_sptr self) -> std::string"""
        return _doa_swig.MUSIC_lin_array_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(MUSIC_lin_array_sptr self, std::string name)"""
        return _doa_swig.MUSIC_lin_array_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(MUSIC_lin_array_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.MUSIC_lin_array_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(MUSIC_lin_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.MUSIC_lin_array_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(MUSIC_lin_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.MUSIC_lin_array_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(MUSIC_lin_array_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.MUSIC_lin_array_sptr_message_subscribers(self, which_port)

# Register MUSIC_lin_array_sptr in _doa_swig:
_doa_swig.MUSIC_lin_array_sptr_swigregister(MUSIC_lin_array_sptr)


MUSIC_lin_array_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
MUSIC_lin_array = MUSIC_lin_array.make;

class rootMUSIC_linear_array(object):
    r"""Proxy of C++ gr::doa::rootMUSIC_linear_array class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(norm_spacing: "float", num_targets: "int", num_ant_ele: "int") -> "gr::doa::rootMUSIC_linear_array::sptr":
        r"""make(float norm_spacing, int num_targets, int num_ant_ele) -> rootMUSIC_linear_array_sptr"""
        return _doa_swig.rootMUSIC_linear_array_make(norm_spacing, num_targets, num_ant_ele)
    __swig_destroy__ = _doa_swig.delete_rootMUSIC_linear_array

# Register rootMUSIC_linear_array in _doa_swig:
_doa_swig.rootMUSIC_linear_array_swigregister(rootMUSIC_linear_array)

def rootMUSIC_linear_array_make(norm_spacing: "float", num_targets: "int", num_ant_ele: "int") -> "gr::doa::rootMUSIC_linear_array::sptr":
    r"""rootMUSIC_linear_array_make(float norm_spacing, int num_targets, int num_ant_ele) -> rootMUSIC_linear_array_sptr"""
    return _doa_swig.rootMUSIC_linear_array_make(norm_spacing, num_targets, num_ant_ele)

class rootMUSIC_linear_array_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::rootMUSIC_linear_array > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(rootMUSIC_linear_array_sptr self) -> rootMUSIC_linear_array_sptr
        __init__(rootMUSIC_linear_array_sptr self, rootMUSIC_linear_array p) -> rootMUSIC_linear_array_sptr
        """
        _doa_swig.rootMUSIC_linear_array_sptr_swiginit(self, _doa_swig.new_rootMUSIC_linear_array_sptr(*args))

    def __deref__(self) -> "gr::doa::rootMUSIC_linear_array *":
        r"""__deref__(rootMUSIC_linear_array_sptr self) -> rootMUSIC_linear_array"""
        return _doa_swig.rootMUSIC_linear_array_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_rootMUSIC_linear_array_sptr

    def make(self, norm_spacing: "float", num_targets: "int", num_ant_ele: "int") -> "gr::doa::rootMUSIC_linear_array::sptr":
        r"""make(rootMUSIC_linear_array_sptr self, float norm_spacing, int num_targets, int num_ant_ele) -> rootMUSIC_linear_array_sptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_make(self, norm_spacing, num_targets, num_ant_ele)

    def history(self) -> "unsigned int":
        r"""history(rootMUSIC_linear_array_sptr self) -> unsigned int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(rootMUSIC_linear_array_sptr self, int which, int delay)
        declare_sample_delay(rootMUSIC_linear_array_sptr self, unsigned int delay)
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(rootMUSIC_linear_array_sptr self, int which) -> unsigned int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(rootMUSIC_linear_array_sptr self, int multiple)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(rootMUSIC_linear_array_sptr self) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(rootMUSIC_linear_array_sptr self) -> double"""
        return _doa_swig.rootMUSIC_linear_array_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(rootMUSIC_linear_array_sptr self) -> uint64_t"""
        return _doa_swig.rootMUSIC_linear_array_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(rootMUSIC_linear_array_sptr self) -> uint64_t"""
        return _doa_swig.rootMUSIC_linear_array_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(rootMUSIC_linear_array_sptr self) -> bool"""
        return _doa_swig.rootMUSIC_linear_array_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(rootMUSIC_linear_array_sptr self) -> bool"""
        return _doa_swig.rootMUSIC_linear_array_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(rootMUSIC_linear_array_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.rootMUSIC_linear_array_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(rootMUSIC_linear_array_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.rootMUSIC_linear_array_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(rootMUSIC_linear_array_sptr self, std::string level)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(rootMUSIC_linear_array_sptr self) -> std::string"""
        return _doa_swig.rootMUSIC_linear_array_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(rootMUSIC_linear_array_sptr self) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(rootMUSIC_linear_array_sptr self, int m)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(rootMUSIC_linear_array_sptr self)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(rootMUSIC_linear_array_sptr self) -> bool"""
        return _doa_swig.rootMUSIC_linear_array_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(rootMUSIC_linear_array_sptr self, int m)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(rootMUSIC_linear_array_sptr self) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(rootMUSIC_linear_array_sptr self, int i) -> long"""
        return _doa_swig.rootMUSIC_linear_array_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(rootMUSIC_linear_array_sptr self, long max_output_buffer)
        set_max_output_buffer(rootMUSIC_linear_array_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(rootMUSIC_linear_array_sptr self, int i) -> long"""
        return _doa_swig.rootMUSIC_linear_array_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(rootMUSIC_linear_array_sptr self, long min_output_buffer)
        set_min_output_buffer(rootMUSIC_linear_array_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_input_buffers_full(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_input_buffers_full_avg(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_input_buffers_full_var(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_output_buffers_full(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_output_buffers_full_avg(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(rootMUSIC_linear_array_sptr self, int which) -> float
        pc_output_buffers_full_var(rootMUSIC_linear_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(rootMUSIC_linear_array_sptr self) -> float"""
        return _doa_swig.rootMUSIC_linear_array_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(rootMUSIC_linear_array_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(rootMUSIC_linear_array_sptr self)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(rootMUSIC_linear_array_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.rootMUSIC_linear_array_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(rootMUSIC_linear_array_sptr self) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(rootMUSIC_linear_array_sptr self) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(rootMUSIC_linear_array_sptr self, int priority) -> int"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(rootMUSIC_linear_array_sptr self) -> std::string"""
        return _doa_swig.rootMUSIC_linear_array_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(rootMUSIC_linear_array_sptr self) -> std::string"""
        return _doa_swig.rootMUSIC_linear_array_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(rootMUSIC_linear_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(rootMUSIC_linear_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(rootMUSIC_linear_array_sptr self) -> long"""
        return _doa_swig.rootMUSIC_linear_array_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(rootMUSIC_linear_array_sptr self) -> basic_block_sptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(rootMUSIC_linear_array_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.rootMUSIC_linear_array_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(rootMUSIC_linear_array_sptr self) -> std::string"""
        return _doa_swig.rootMUSIC_linear_array_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(rootMUSIC_linear_array_sptr self, std::string name)"""
        return _doa_swig.rootMUSIC_linear_array_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(rootMUSIC_linear_array_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.rootMUSIC_linear_array_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(rootMUSIC_linear_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(rootMUSIC_linear_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(rootMUSIC_linear_array_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.rootMUSIC_linear_array_sptr_message_subscribers(self, which_port)

# Register rootMUSIC_linear_array_sptr in _doa_swig:
_doa_swig.rootMUSIC_linear_array_sptr_swigregister(rootMUSIC_linear_array_sptr)


rootMUSIC_linear_array_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
rootMUSIC_linear_array = rootMUSIC_linear_array.make;

class antenna_correction(object):
    r"""Proxy of C++ gr::doa::antenna_correction class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(num_ant_ele: "int", config_filename: "char *") -> "gr::doa::antenna_correction::sptr":
        r"""make(int num_ant_ele, char * config_filename) -> antenna_correction_sptr"""
        return _doa_swig.antenna_correction_make(num_ant_ele, config_filename)
    __swig_destroy__ = _doa_swig.delete_antenna_correction

# Register antenna_correction in _doa_swig:
_doa_swig.antenna_correction_swigregister(antenna_correction)

def antenna_correction_make(num_ant_ele: "int", config_filename: "char *") -> "gr::doa::antenna_correction::sptr":
    r"""antenna_correction_make(int num_ant_ele, char * config_filename) -> antenna_correction_sptr"""
    return _doa_swig.antenna_correction_make(num_ant_ele, config_filename)

class antenna_correction_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::antenna_correction > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(antenna_correction_sptr self) -> antenna_correction_sptr
        __init__(antenna_correction_sptr self, antenna_correction p) -> antenna_correction_sptr
        """
        _doa_swig.antenna_correction_sptr_swiginit(self, _doa_swig.new_antenna_correction_sptr(*args))

    def __deref__(self) -> "gr::doa::antenna_correction *":
        r"""__deref__(antenna_correction_sptr self) -> antenna_correction"""
        return _doa_swig.antenna_correction_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_antenna_correction_sptr

    def make(self, num_ant_ele: "int", config_filename: "char *") -> "gr::doa::antenna_correction::sptr":
        r"""make(antenna_correction_sptr self, int num_ant_ele, char * config_filename) -> antenna_correction_sptr"""
        return _doa_swig.antenna_correction_sptr_make(self, num_ant_ele, config_filename)

    def history(self) -> "unsigned int":
        r"""history(antenna_correction_sptr self) -> unsigned int"""
        return _doa_swig.antenna_correction_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(antenna_correction_sptr self, int which, int delay)
        declare_sample_delay(antenna_correction_sptr self, unsigned int delay)
        """
        return _doa_swig.antenna_correction_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(antenna_correction_sptr self, int which) -> unsigned int"""
        return _doa_swig.antenna_correction_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(antenna_correction_sptr self, int multiple)"""
        return _doa_swig.antenna_correction_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(antenna_correction_sptr self) -> int"""
        return _doa_swig.antenna_correction_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(antenna_correction_sptr self) -> double"""
        return _doa_swig.antenna_correction_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(antenna_correction_sptr self) -> uint64_t"""
        return _doa_swig.antenna_correction_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(antenna_correction_sptr self) -> uint64_t"""
        return _doa_swig.antenna_correction_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(antenna_correction_sptr self) -> bool"""
        return _doa_swig.antenna_correction_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(antenna_correction_sptr self) -> bool"""
        return _doa_swig.antenna_correction_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(antenna_correction_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.antenna_correction_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(antenna_correction_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.antenna_correction_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(antenna_correction_sptr self, std::string level)"""
        return _doa_swig.antenna_correction_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(antenna_correction_sptr self) -> std::string"""
        return _doa_swig.antenna_correction_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(antenna_correction_sptr self) -> int"""
        return _doa_swig.antenna_correction_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(antenna_correction_sptr self, int m)"""
        return _doa_swig.antenna_correction_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(antenna_correction_sptr self)"""
        return _doa_swig.antenna_correction_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(antenna_correction_sptr self) -> bool"""
        return _doa_swig.antenna_correction_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(antenna_correction_sptr self, int m)"""
        return _doa_swig.antenna_correction_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(antenna_correction_sptr self) -> int"""
        return _doa_swig.antenna_correction_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(antenna_correction_sptr self, int i) -> long"""
        return _doa_swig.antenna_correction_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(antenna_correction_sptr self, long max_output_buffer)
        set_max_output_buffer(antenna_correction_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.antenna_correction_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(antenna_correction_sptr self, int i) -> long"""
        return _doa_swig.antenna_correction_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(antenna_correction_sptr self, long min_output_buffer)
        set_min_output_buffer(antenna_correction_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.antenna_correction_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(antenna_correction_sptr self, int which) -> float
        pc_input_buffers_full(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(antenna_correction_sptr self, int which) -> float
        pc_input_buffers_full_avg(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(antenna_correction_sptr self, int which) -> float
        pc_input_buffers_full_var(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(antenna_correction_sptr self, int which) -> float
        pc_output_buffers_full(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(antenna_correction_sptr self, int which) -> float
        pc_output_buffers_full_avg(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(antenna_correction_sptr self, int which) -> float
        pc_output_buffers_full_var(antenna_correction_sptr self) -> pmt_vector_float
        """
        return _doa_swig.antenna_correction_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(antenna_correction_sptr self) -> float"""
        return _doa_swig.antenna_correction_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(antenna_correction_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.antenna_correction_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(antenna_correction_sptr self)"""
        return _doa_swig.antenna_correction_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(antenna_correction_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.antenna_correction_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(antenna_correction_sptr self) -> int"""
        return _doa_swig.antenna_correction_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(antenna_correction_sptr self) -> int"""
        return _doa_swig.antenna_correction_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(antenna_correction_sptr self, int priority) -> int"""
        return _doa_swig.antenna_correction_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(antenna_correction_sptr self) -> std::string"""
        return _doa_swig.antenna_correction_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(antenna_correction_sptr self) -> std::string"""
        return _doa_swig.antenna_correction_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(antenna_correction_sptr self) -> io_signature_sptr"""
        return _doa_swig.antenna_correction_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(antenna_correction_sptr self) -> io_signature_sptr"""
        return _doa_swig.antenna_correction_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(antenna_correction_sptr self) -> long"""
        return _doa_swig.antenna_correction_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(antenna_correction_sptr self) -> basic_block_sptr"""
        return _doa_swig.antenna_correction_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(antenna_correction_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.antenna_correction_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(antenna_correction_sptr self) -> std::string"""
        return _doa_swig.antenna_correction_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(antenna_correction_sptr self, std::string name)"""
        return _doa_swig.antenna_correction_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(antenna_correction_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.antenna_correction_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(antenna_correction_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.antenna_correction_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(antenna_correction_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.antenna_correction_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(antenna_correction_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.antenna_correction_sptr_message_subscribers(self, which_port)

# Register antenna_correction_sptr in _doa_swig:
_doa_swig.antenna_correction_sptr_swigregister(antenna_correction_sptr)


antenna_correction_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
antenna_correction = antenna_correction.make;

class find_local_max(object):
    r"""Proxy of C++ gr::doa::find_local_max class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(num_max_vals: "int", vector_len: "int", x_min: "float", x_max: "float") -> "gr::doa::find_local_max::sptr":
        r"""make(int num_max_vals, int vector_len, float x_min, float x_max) -> find_local_max_sptr"""
        return _doa_swig.find_local_max_make(num_max_vals, vector_len, x_min, x_max)
    __swig_destroy__ = _doa_swig.delete_find_local_max

# Register find_local_max in _doa_swig:
_doa_swig.find_local_max_swigregister(find_local_max)

def find_local_max_make(num_max_vals: "int", vector_len: "int", x_min: "float", x_max: "float") -> "gr::doa::find_local_max::sptr":
    r"""find_local_max_make(int num_max_vals, int vector_len, float x_min, float x_max) -> find_local_max_sptr"""
    return _doa_swig.find_local_max_make(num_max_vals, vector_len, x_min, x_max)

class find_local_max_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::find_local_max > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(find_local_max_sptr self) -> find_local_max_sptr
        __init__(find_local_max_sptr self, find_local_max p) -> find_local_max_sptr
        """
        _doa_swig.find_local_max_sptr_swiginit(self, _doa_swig.new_find_local_max_sptr(*args))

    def __deref__(self) -> "gr::doa::find_local_max *":
        r"""__deref__(find_local_max_sptr self) -> find_local_max"""
        return _doa_swig.find_local_max_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_find_local_max_sptr

    def make(self, num_max_vals: "int", vector_len: "int", x_min: "float", x_max: "float") -> "gr::doa::find_local_max::sptr":
        r"""make(find_local_max_sptr self, int num_max_vals, int vector_len, float x_min, float x_max) -> find_local_max_sptr"""
        return _doa_swig.find_local_max_sptr_make(self, num_max_vals, vector_len, x_min, x_max)

    def history(self) -> "unsigned int":
        r"""history(find_local_max_sptr self) -> unsigned int"""
        return _doa_swig.find_local_max_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(find_local_max_sptr self, int which, int delay)
        declare_sample_delay(find_local_max_sptr self, unsigned int delay)
        """
        return _doa_swig.find_local_max_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(find_local_max_sptr self, int which) -> unsigned int"""
        return _doa_swig.find_local_max_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(find_local_max_sptr self, int multiple)"""
        return _doa_swig.find_local_max_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(find_local_max_sptr self) -> int"""
        return _doa_swig.find_local_max_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(find_local_max_sptr self) -> double"""
        return _doa_swig.find_local_max_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(find_local_max_sptr self) -> uint64_t"""
        return _doa_swig.find_local_max_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(find_local_max_sptr self) -> uint64_t"""
        return _doa_swig.find_local_max_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(find_local_max_sptr self) -> bool"""
        return _doa_swig.find_local_max_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(find_local_max_sptr self) -> bool"""
        return _doa_swig.find_local_max_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(find_local_max_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.find_local_max_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(find_local_max_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.find_local_max_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(find_local_max_sptr self, std::string level)"""
        return _doa_swig.find_local_max_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(find_local_max_sptr self) -> std::string"""
        return _doa_swig.find_local_max_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(find_local_max_sptr self) -> int"""
        return _doa_swig.find_local_max_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(find_local_max_sptr self, int m)"""
        return _doa_swig.find_local_max_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(find_local_max_sptr self)"""
        return _doa_swig.find_local_max_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(find_local_max_sptr self) -> bool"""
        return _doa_swig.find_local_max_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(find_local_max_sptr self, int m)"""
        return _doa_swig.find_local_max_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(find_local_max_sptr self) -> int"""
        return _doa_swig.find_local_max_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(find_local_max_sptr self, int i) -> long"""
        return _doa_swig.find_local_max_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(find_local_max_sptr self, long max_output_buffer)
        set_max_output_buffer(find_local_max_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.find_local_max_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(find_local_max_sptr self, int i) -> long"""
        return _doa_swig.find_local_max_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(find_local_max_sptr self, long min_output_buffer)
        set_min_output_buffer(find_local_max_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.find_local_max_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(find_local_max_sptr self, int which) -> float
        pc_input_buffers_full(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(find_local_max_sptr self, int which) -> float
        pc_input_buffers_full_avg(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(find_local_max_sptr self, int which) -> float
        pc_input_buffers_full_var(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(find_local_max_sptr self, int which) -> float
        pc_output_buffers_full(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(find_local_max_sptr self, int which) -> float
        pc_output_buffers_full_avg(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(find_local_max_sptr self, int which) -> float
        pc_output_buffers_full_var(find_local_max_sptr self) -> pmt_vector_float
        """
        return _doa_swig.find_local_max_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(find_local_max_sptr self) -> float"""
        return _doa_swig.find_local_max_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(find_local_max_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.find_local_max_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(find_local_max_sptr self)"""
        return _doa_swig.find_local_max_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(find_local_max_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.find_local_max_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(find_local_max_sptr self) -> int"""
        return _doa_swig.find_local_max_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(find_local_max_sptr self) -> int"""
        return _doa_swig.find_local_max_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(find_local_max_sptr self, int priority) -> int"""
        return _doa_swig.find_local_max_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(find_local_max_sptr self) -> std::string"""
        return _doa_swig.find_local_max_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(find_local_max_sptr self) -> std::string"""
        return _doa_swig.find_local_max_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(find_local_max_sptr self) -> io_signature_sptr"""
        return _doa_swig.find_local_max_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(find_local_max_sptr self) -> io_signature_sptr"""
        return _doa_swig.find_local_max_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(find_local_max_sptr self) -> long"""
        return _doa_swig.find_local_max_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(find_local_max_sptr self) -> basic_block_sptr"""
        return _doa_swig.find_local_max_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(find_local_max_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.find_local_max_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(find_local_max_sptr self) -> std::string"""
        return _doa_swig.find_local_max_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(find_local_max_sptr self, std::string name)"""
        return _doa_swig.find_local_max_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(find_local_max_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.find_local_max_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(find_local_max_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.find_local_max_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(find_local_max_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.find_local_max_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(find_local_max_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.find_local_max_sptr_message_subscribers(self, which_port)

# Register find_local_max_sptr in _doa_swig:
_doa_swig.find_local_max_sptr_swigregister(find_local_max_sptr)


find_local_max_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
find_local_max = find_local_max.make;

class calibrate_lin_array(object):
    r"""Proxy of C++ gr::doa::calibrate_lin_array class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def make(norm_spacing: "float", num_ant_ele: "int", pilot_angle: "float") -> "gr::doa::calibrate_lin_array::sptr":
        r"""make(float norm_spacing, int num_ant_ele, float pilot_angle) -> calibrate_lin_array_sptr"""
        return _doa_swig.calibrate_lin_array_make(norm_spacing, num_ant_ele, pilot_angle)
    __swig_destroy__ = _doa_swig.delete_calibrate_lin_array

# Register calibrate_lin_array in _doa_swig:
_doa_swig.calibrate_lin_array_swigregister(calibrate_lin_array)

def calibrate_lin_array_make(norm_spacing: "float", num_ant_ele: "int", pilot_angle: "float") -> "gr::doa::calibrate_lin_array::sptr":
    r"""calibrate_lin_array_make(float norm_spacing, int num_ant_ele, float pilot_angle) -> calibrate_lin_array_sptr"""
    return _doa_swig.calibrate_lin_array_make(norm_spacing, num_ant_ele, pilot_angle)

class calibrate_lin_array_sptr(object):
    r"""Proxy of C++ boost::shared_ptr< gr::doa::calibrate_lin_array > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        r"""
        __init__(calibrate_lin_array_sptr self) -> calibrate_lin_array_sptr
        __init__(calibrate_lin_array_sptr self, calibrate_lin_array p) -> calibrate_lin_array_sptr
        """
        _doa_swig.calibrate_lin_array_sptr_swiginit(self, _doa_swig.new_calibrate_lin_array_sptr(*args))

    def __deref__(self) -> "gr::doa::calibrate_lin_array *":
        r"""__deref__(calibrate_lin_array_sptr self) -> calibrate_lin_array"""
        return _doa_swig.calibrate_lin_array_sptr___deref__(self)
    __swig_destroy__ = _doa_swig.delete_calibrate_lin_array_sptr

    def make(self, norm_spacing: "float", num_ant_ele: "int", pilot_angle: "float") -> "gr::doa::calibrate_lin_array::sptr":
        r"""make(calibrate_lin_array_sptr self, float norm_spacing, int num_ant_ele, float pilot_angle) -> calibrate_lin_array_sptr"""
        return _doa_swig.calibrate_lin_array_sptr_make(self, norm_spacing, num_ant_ele, pilot_angle)

    def history(self) -> "unsigned int":
        r"""history(calibrate_lin_array_sptr self) -> unsigned int"""
        return _doa_swig.calibrate_lin_array_sptr_history(self)

    def declare_sample_delay(self, *args) -> "void":
        r"""
        declare_sample_delay(calibrate_lin_array_sptr self, int which, int delay)
        declare_sample_delay(calibrate_lin_array_sptr self, unsigned int delay)
        """
        return _doa_swig.calibrate_lin_array_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, which: "int") -> "unsigned int":
        r"""sample_delay(calibrate_lin_array_sptr self, int which) -> unsigned int"""
        return _doa_swig.calibrate_lin_array_sptr_sample_delay(self, which)

    def set_output_multiple(self, multiple: "int") -> "void":
        r"""set_output_multiple(calibrate_lin_array_sptr self, int multiple)"""
        return _doa_swig.calibrate_lin_array_sptr_set_output_multiple(self, multiple)

    def output_multiple(self) -> "int":
        r"""output_multiple(calibrate_lin_array_sptr self) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_output_multiple(self)

    def relative_rate(self) -> "double":
        r"""relative_rate(calibrate_lin_array_sptr self) -> double"""
        return _doa_swig.calibrate_lin_array_sptr_relative_rate(self)

    def relative_rate_i(self) -> "uint64_t":
        r"""relative_rate_i(calibrate_lin_array_sptr self) -> uint64_t"""
        return _doa_swig.calibrate_lin_array_sptr_relative_rate_i(self)

    def relative_rate_d(self) -> "uint64_t":
        r"""relative_rate_d(calibrate_lin_array_sptr self) -> uint64_t"""
        return _doa_swig.calibrate_lin_array_sptr_relative_rate_d(self)

    def start(self) -> "bool":
        r"""start(calibrate_lin_array_sptr self) -> bool"""
        return _doa_swig.calibrate_lin_array_sptr_start(self)

    def stop(self) -> "bool":
        r"""stop(calibrate_lin_array_sptr self) -> bool"""
        return _doa_swig.calibrate_lin_array_sptr_stop(self)

    def nitems_read(self, which_input: "unsigned int") -> "uint64_t":
        r"""nitems_read(calibrate_lin_array_sptr self, unsigned int which_input) -> uint64_t"""
        return _doa_swig.calibrate_lin_array_sptr_nitems_read(self, which_input)

    def nitems_written(self, which_output: "unsigned int") -> "uint64_t":
        r"""nitems_written(calibrate_lin_array_sptr self, unsigned int which_output) -> uint64_t"""
        return _doa_swig.calibrate_lin_array_sptr_nitems_written(self, which_output)

    def set_log_level(self, level: "std::string") -> "void":
        r"""set_log_level(calibrate_lin_array_sptr self, std::string level)"""
        return _doa_swig.calibrate_lin_array_sptr_set_log_level(self, level)

    def log_level(self) -> "std::string":
        r"""log_level(calibrate_lin_array_sptr self) -> std::string"""
        return _doa_swig.calibrate_lin_array_sptr_log_level(self)

    def max_noutput_items(self) -> "int":
        r"""max_noutput_items(calibrate_lin_array_sptr self) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, m: "int") -> "void":
        r"""set_max_noutput_items(calibrate_lin_array_sptr self, int m)"""
        return _doa_swig.calibrate_lin_array_sptr_set_max_noutput_items(self, m)

    def unset_max_noutput_items(self) -> "void":
        r"""unset_max_noutput_items(calibrate_lin_array_sptr self)"""
        return _doa_swig.calibrate_lin_array_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self) -> "bool":
        r"""is_set_max_noutput_items(calibrate_lin_array_sptr self) -> bool"""
        return _doa_swig.calibrate_lin_array_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, m: "int") -> "void":
        r"""set_min_noutput_items(calibrate_lin_array_sptr self, int m)"""
        return _doa_swig.calibrate_lin_array_sptr_set_min_noutput_items(self, m)

    def min_noutput_items(self) -> "int":
        r"""min_noutput_items(calibrate_lin_array_sptr self) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_min_noutput_items(self)

    def max_output_buffer(self, i: "int") -> "long":
        r"""max_output_buffer(calibrate_lin_array_sptr self, int i) -> long"""
        return _doa_swig.calibrate_lin_array_sptr_max_output_buffer(self, i)

    def set_max_output_buffer(self, *args) -> "void":
        r"""
        set_max_output_buffer(calibrate_lin_array_sptr self, long max_output_buffer)
        set_max_output_buffer(calibrate_lin_array_sptr self, int port, long max_output_buffer)
        """
        return _doa_swig.calibrate_lin_array_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, i: "int") -> "long":
        r"""min_output_buffer(calibrate_lin_array_sptr self, int i) -> long"""
        return _doa_swig.calibrate_lin_array_sptr_min_output_buffer(self, i)

    def set_min_output_buffer(self, *args) -> "void":
        r"""
        set_min_output_buffer(calibrate_lin_array_sptr self, long min_output_buffer)
        set_min_output_buffer(calibrate_lin_array_sptr self, int port, long min_output_buffer)
        """
        return _doa_swig.calibrate_lin_array_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self) -> "float":
        r"""pc_noutput_items(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self) -> "float":
        r"""pc_noutput_items_avg(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self) -> "float":
        r"""pc_noutput_items_var(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self) -> "float":
        r"""pc_nproduced(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self) -> "float":
        r"""pc_nproduced_avg(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self) -> "float":
        r"""pc_nproduced_var(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full(calibrate_lin_array_sptr self, int which) -> float
        pc_input_buffers_full(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_avg(calibrate_lin_array_sptr self, int which) -> float
        pc_input_buffers_full_avg(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_input_buffers_full_var(calibrate_lin_array_sptr self, int which) -> float
        pc_input_buffers_full_var(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full(calibrate_lin_array_sptr self, int which) -> float
        pc_output_buffers_full(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_avg(calibrate_lin_array_sptr self, int which) -> float
        pc_output_buffers_full_avg(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args) -> "std::vector< float,std::allocator< float > >":
        r"""
        pc_output_buffers_full_var(calibrate_lin_array_sptr self, int which) -> float
        pc_output_buffers_full_var(calibrate_lin_array_sptr self) -> pmt_vector_float
        """
        return _doa_swig.calibrate_lin_array_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self) -> "float":
        r"""pc_work_time(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_work_time(self)

    def pc_work_time_avg(self) -> "float":
        r"""pc_work_time_avg(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self) -> "float":
        r"""pc_work_time_var(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_work_time_var(self)

    def pc_work_time_total(self) -> "float":
        r"""pc_work_time_total(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self) -> "float":
        r"""pc_throughput_avg(calibrate_lin_array_sptr self) -> float"""
        return _doa_swig.calibrate_lin_array_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, mask: "std::vector< int,std::allocator< int > > const &") -> "void":
        r"""set_processor_affinity(calibrate_lin_array_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _doa_swig.calibrate_lin_array_sptr_set_processor_affinity(self, mask)

    def unset_processor_affinity(self) -> "void":
        r"""unset_processor_affinity(calibrate_lin_array_sptr self)"""
        return _doa_swig.calibrate_lin_array_sptr_unset_processor_affinity(self)

    def processor_affinity(self) -> "std::vector< int,std::allocator< int > >":
        r"""processor_affinity(calibrate_lin_array_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _doa_swig.calibrate_lin_array_sptr_processor_affinity(self)

    def active_thread_priority(self) -> "int":
        r"""active_thread_priority(calibrate_lin_array_sptr self) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_active_thread_priority(self)

    def thread_priority(self) -> "int":
        r"""thread_priority(calibrate_lin_array_sptr self) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_thread_priority(self)

    def set_thread_priority(self, priority: "int") -> "int":
        r"""set_thread_priority(calibrate_lin_array_sptr self, int priority) -> int"""
        return _doa_swig.calibrate_lin_array_sptr_set_thread_priority(self, priority)

    def name(self) -> "std::string":
        r"""name(calibrate_lin_array_sptr self) -> std::string"""
        return _doa_swig.calibrate_lin_array_sptr_name(self)

    def symbol_name(self) -> "std::string":
        r"""symbol_name(calibrate_lin_array_sptr self) -> std::string"""
        return _doa_swig.calibrate_lin_array_sptr_symbol_name(self)

    def input_signature(self) -> "gr::io_signature::sptr":
        r"""input_signature(calibrate_lin_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.calibrate_lin_array_sptr_input_signature(self)

    def output_signature(self) -> "gr::io_signature::sptr":
        r"""output_signature(calibrate_lin_array_sptr self) -> io_signature_sptr"""
        return _doa_swig.calibrate_lin_array_sptr_output_signature(self)

    def unique_id(self) -> "long":
        r"""unique_id(calibrate_lin_array_sptr self) -> long"""
        return _doa_swig.calibrate_lin_array_sptr_unique_id(self)

    def to_basic_block(self) -> "gr::basic_block_sptr":
        r"""to_basic_block(calibrate_lin_array_sptr self) -> basic_block_sptr"""
        return _doa_swig.calibrate_lin_array_sptr_to_basic_block(self)

    def check_topology(self, ninputs: "int", noutputs: "int") -> "bool":
        r"""check_topology(calibrate_lin_array_sptr self, int ninputs, int noutputs) -> bool"""
        return _doa_swig.calibrate_lin_array_sptr_check_topology(self, ninputs, noutputs)

    def alias(self) -> "std::string":
        r"""alias(calibrate_lin_array_sptr self) -> std::string"""
        return _doa_swig.calibrate_lin_array_sptr_alias(self)

    def set_block_alias(self, name: "std::string") -> "void":
        r"""set_block_alias(calibrate_lin_array_sptr self, std::string name)"""
        return _doa_swig.calibrate_lin_array_sptr_set_block_alias(self, name)

    def _post(self, which_port: "swig_pmt_ptr", msg: "swig_pmt_ptr") -> "void":
        r"""_post(calibrate_lin_array_sptr self, swig_pmt_ptr which_port, swig_pmt_ptr msg)"""
        return _doa_swig.calibrate_lin_array_sptr__post(self, which_port, msg)

    def message_ports_in(self) -> "pmt::pmt_t":
        r"""message_ports_in(calibrate_lin_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.calibrate_lin_array_sptr_message_ports_in(self)

    def message_ports_out(self) -> "pmt::pmt_t":
        r"""message_ports_out(calibrate_lin_array_sptr self) -> swig_pmt_ptr"""
        return _doa_swig.calibrate_lin_array_sptr_message_ports_out(self)

    def message_subscribers(self, which_port: "swig_pmt_ptr") -> "pmt::pmt_t":
        r"""message_subscribers(calibrate_lin_array_sptr self, swig_pmt_ptr which_port) -> swig_pmt_ptr"""
        return _doa_swig.calibrate_lin_array_sptr_message_subscribers(self, which_port)

# Register calibrate_lin_array_sptr in _doa_swig:
_doa_swig.calibrate_lin_array_sptr_swigregister(calibrate_lin_array_sptr)


calibrate_lin_array_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
calibrate_lin_array = calibrate_lin_array.make;



